firstName = input("Cual es tu nombre? ")
lastName = input("Cual es tu apellido? ")
seccion = input("Cual es tu seccion? ")
sede = input("Cual es tu sede? ")
print("Hola " + firstName, lastName + "! Eres estudiante de la seccion "+ seccion +" en la sede "+ sede +".")